type = "cron"
schemaVersion = 1
name = "genstatehashipfscid"
schedule = "CRON_TZ=UTC 0 30 19 * * *"
observationSource = """
    gen_statehash_ipfscid [type=bridge name="gooddollar-bridge" requestData="{\\"data\\": {\\"endpoint\\":\\"genstatehashipfscid\\"}}"]

    gen_statehash_ipfscid 
"""
